### PR TITLE
Adds sonarcloud infos to the pom

### PR DESCRIPTION
**Pull request by Kerruba**

### CODE REVIEW

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by Kerruba** [comment]
Retest this please

**Comment by entando-service** [comment]
Something went wrong. Investigate!

**Comment by Kerruba** [comment]
Retest this please

**Comment by entando-service** [comment]
All is well

**Comment by Kerruba** [comment]
retest this please

**Comment by entando-service** [comment]
All is well

**Pull request merged**
