### PR TITLE
Migrated to entando-k8s-custom-model

### PR DESCRIPTION
**Pull request by ampie**
Luca I migrated this to entando-k8s-custom-model, but it seems to have changed the "plugins" attribute on the HATEOAS resource list... Please can you have a look for me? Or if it doesn't matter, I guess you can merge the PR.

### CODE REVIEW

**Comment by entando-service** [comment]
All is well

**Comment by ampie** [comment]
Try again

**Comment by entando-service** [comment]
All is well

**Comment by Kerruba** [comment]
We can think of changing the response in the future, atm let's keep it this way

**Pull request merged**
